import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbars/Navbar";
import MobileTabletNavbar from "@/components/navbars/MobileTabletNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog User App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="drawer">
          <input id="my-drawer" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content">
            {/* Page content here */}
            {/* navbar */}
            <Navbar />
            {/* <MobileTabletNavbar /> */}
            {/* body */}
            <div className="flex min-h-screen flex-col items-center justify-between  p-4 ">
              {children}
            </div>
          </div>
          <div className="drawer-side">
            <label
              htmlFor="my-drawer"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
              {/* Sidebar content here */}
              <li>
                <a>Sidebar Item 1</a>
              </li>
              <li>
                <a>Sidebar Item 2</a>
              </li>
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
